services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app:delegated
      - bun-cache:/root/.bun
      - /app/node_modules
    ports:
      - "5173:5173"
    command: bun run dev

volumes:
  bun-cache:
