name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate release changes
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_A_SECRET }}
        run: bun run release

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PROJECT_A_SECRET }}
          commit-message: "chore(release): prepare for next version"
          title: "chore(release): prepare for next version"
          body: "This PR prepares the project for the next release.\n\nPlease review and approve."
          branch: release/next
          base: main
          labels: release
